#!/bin/bash

cmake -B Fbuild \
-D CMAKE_INSTALL_PREFIX:PATH=/app \
-D Trilinos_ENABLE_CXX11=ON \
-D Trilinos_ENABLE_Fortran=OFF \
-D BUILD_SHARED_LIBS=ON \
-D TPL_ENABLE_BLAS=ON \
-D BLAS_LIBRARY_DIRS='/app/lib;/app/lib64' \
-D LAPACK_LIBRARY_DIRS='/app/lib;/app/lib64' \
-D TPL_ENABLE_Boost=ON \
-D TPL_ENABLE_Cholmod=ON \
-D TPL_ENABLE_SCALAPACK=OFF \
-D SCALAPACK_LIBRARY_NAMES='libscalapack-openmpi.so' \
-D TPL_ENABLE_ParMETIS=OFF \
-D TPL_ENABLE_MUMPS=OFF \
-D TPL_ENABLE_SuperLU=OFF \
-D TPL_ENABLE_UMFPACK=OFF \
-D TPL_BLAS_INCLUDE_DIRS=/app/include/suitesparse \
-D TPL_Cholmod_INCLUDE_DIRS=/app/include/suitesparse \
-D TPL_Cholmod_LIBRARIES='/app/lib/libcholmod.so;/app/lib/libamd.so;/app/lib/libcolamd.so' \
-D TPL_UMFPACK_INCLUDE_DIRS=/app/include/suitesparse \
-D TPL_Boost_INCLUDE_DIRS=/app/include/boost \
-D TPL_Boost_LIBRARY_DIRS=lib \
-D Trilinos_ENABLE_Amesos=ON \
-D Trilinos_ENABLE_Amesos2=ON \
-D Trilinos_ENABLE_AztecOO=ON \
-D Trilinos_ENABLE_Belos=ON \
-D Trilinos_ENABLE_Ifpack=ON \
-D Trilinos_ENABLE_Ifpack2=ON \
-D Trilinos_ENABLE_Kokkos=ON \
-D Trilinos_ENABLE_Komplex=ON \
-D Trilinos_ENABLE_ML=ON \
-D Trilinos_ENABLE_MueLu=ON \
-D Trilinos_ENABLE_Teuchos=ON \
-D Trilinos_ENABLE_Tpetra=ON \
-D Trilinos_ENABLE_ALL_OPTIONAL_PACKAGES=ON \
-D Kokkos_ENABLE_AGGRESSIVE_VECTORIZATION=ON \
-D Tpetra_INST_COMPLEX_DOUBLE=ON \
-D Trilinos_ENABLE_COMPLEX_DOUBLE=ON \
-D Teuchos_ENABLE_COMPLEX=ON \
-D Tpetra_INST_INT_INT=ON \
-D Tpetra_ENABLE_DEPRECATED_CODE=ON \
-D Trilinos_ENABLE_OpenMP=ON \
-D TPL_ENABLE_MPI=ON \
-D Trilinos_ENABLE_EXPLICIT_INSTANTIATION=ON \
-D Kokkos_ENABLE_COMPILER_WARNINGS=ON \
-D Amesos2_ENABLE_Basker=ON \
-D Tpetra_INST_SERIAL:BOOL=ON \
-D Trilinos_ENABLE_TESTS=OFF \
-D CMAKE_C_FLAGS="$CFLAGS -Wno-incompatible-pointer-types" \
-D CMAKE_Fortran_FLAGS="$FCFLAGS -fallow-argument-mismatch"

make -j$FLATPAK_BUILDER_N_JOBS VERBOSE=1 -C Fbuild

cmake --install Fbuild
